version: '3'
services:
  db:
    container_name: dbhost
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: OU-Shit
    volumes:
    - /opt/serenity/mysql:/var/lib/mysql

  calm:
    container_name: calm      
    build: ./
    depends_on:
      - db
    ports:
      - "9001:9001"
    volumes:
    - /opt/calm:/files
  web:
    container_name: nginx
    image: nginx:stable
    depends_on:
    - calm

    ports:
      - "80:80"
    volumes:
    - /opt/calm/conf.d:/etc/nginx/conf.d
    - /opt/calm:/files
